title: Leap Day theme
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
layout: default
google_analytics:
collections:
        contributions:
                output: true
                list:
                        title: "It all started in Mexico and Dundee!"
                        url: /contributions/01
                        order: 1

                        title: "Civic Engagement and Collaboration"
                        url: /contributions/02
                        order: 2

                        title: "Coding Mexico"
                        url: /contributions/03
                        order: 3
                defaults:
                        values:
                                layout: default
theme:
