title: Crafting our Digital Future
description: As part of V&A Digital Design Weekend 2015
show_downloads: true
layout: default
url: https://DigiTransGlasgow.github.io/crafting_our_digital_futures/
google_analytics:
list:
        - title: "It all started in Mexico and Dundee!"
          url: /contributions/01
          order: 1

        - title: "Civic Engagement and Collaboration"
          url: /contributions/02
          order: 2

        - title: "Coding Mexico"
          url: /contributions/03
          order: 3
collections:
        contributions:
                output: true
                defaults:
                        values:
                                layout: default
theme:
